// 香气描述是简述；温度、季节、场景与喷法是可调整的个人选香建议。
export const seasons = ['春季', '夏季', '秋季', '冬季'];
export const weathers = ['晴天', '多云', '雨天', '闷热'];
export const scenes = ['日常通勤', '办公室', '周末出门', '约会晚餐', '居家独处'];
export const statuses = { owned: '已有', wishlist: '想买', explore: '待探索' };
export const perfumes = [
  { id: 'cedrus', imageSize: '150 ml', brand: 'CHLOÉ', name: 'Cedrus', cn: '北国雪松', family: '柔和木质', notes: ['雪松', '柔和木香'], mood: '干净的木头，让日常慢下来。', description: '柔和、干燥的木质气息。适合想保持安静、有分寸的日常。', temp: [15, 29], seasons: ['春季', '秋季', '冬季'], weather: ['晴天', '多云', '雨天'], scenes: ['日常通勤', '办公室', '居家独处'], status: 'owned', color: '#a68152', image: './assets/cedrus.png', spray: '个人试穿参考 4–6 喷，分散在锁骨下、前臂等位置；按环境与实际反馈调整。', source: 'https://www.chloe.com/en-gb/p/fragrances/eau-de-parfum/CHCA50217687.html' },
  { id: 'gaiac10', imageSize: '100 ml', image: './assets/gaiac10.jpg', brand: 'LE LABO', name: 'Gaiac 10', cn: '愈创木10', family: '贴肤木质', notes: ['愈创木', '麝香', '焚香'], mood: '温柔、贴肤，留一点自己的空间。', description: '以愈创木与麝香为核心，带有雪松与焚香的气息。安静时更值得细闻。', temp: [12, 26], seasons: ['春季', '秋季', '冬季'], weather: ['多云', '雨天'], scenes: ['办公室', '约会晚餐', '居家独处'], status: 'owned', color: '#816955', spray: '贴肤木质以分散喷点建立存在感；首次试穿后按自己和身边人的实际感受调整用量。', source: 'https://www.lelabofragrances.com/gaiac-10-135.html' },
  { id: 'another13', imageSize: '100 ml', image: './assets/another13.jpg', brand: 'LE LABO', name: 'Another 13', cn: '别样13', family: '清透麝香', notes: ['龙涎香调', '麝香感', '清透感'], mood: '像一件干净衬衫，轻轻陪着你。', description: '清透、抽象的贴肤气息。适合想要干净存在感，又不想太甜的日子。', temp: [16, 32], seasons: ['春季', '夏季', '秋季'], weather: ['晴天', '多云', '雨天', '闷热'], scenes: ['日常通勤', '办公室', '约会晚餐'], status: 'wishlist', color: '#788e99', spray: '个人试穿参考 3–4 喷，清透不代表扩散弱，用旁人的反馈判断是否需要加量。', source: 'https://www.lelabofragrances.com/another-13.html' },
  { id: 'lazySundayMorning', imageSize: '100 ml', image: './assets/lazy-sunday-morning.jpg', brand: 'MAISON MARGIELA', name: 'Lazy Sunday Morning', cn: '慵懒周末', family: '洁净花香', notes: ['铃兰', '鸢尾', '白麝香'], mood: '像周末清晨，刚晒过的柔软床单。', description: 'REPLICA 慵懒周末淡香水（EDT）。铃兰与白麝香带来洁净织物般的气息，鸢尾与黄葵籽添上柔和暖意。', temp: [16, 30], seasons: ['春季', '夏季', '秋季'], weather: ['晴天', '多云', '雨天'], scenes: ['日常通勤', '办公室', '周末出门', '居家独处'], status: 'wishlist', color: '#9c98aa', spray: '个人试穿参考 4–6 喷，分散在锁骨下、前臂等位置；以活动时带出柔和花香为目标。', source: 'https://www.maisonmargiela.com/en-hk/replica-lazy-sunday-morning-eau-de-toilette-S33YX0018S10932001.html' },
  { id: 'imagination', imageSize: '200 ml', image: './assets/imagination.avif', brand: 'LOUIS VUITTON', name: 'Imagination', cn: '思扬', family: '明亮柑橘', notes: ['柑橘', '茶感', '琥珀感'], mood: '明亮、轻快，留给向外走的日子。', description: '想买清单里的夏日明亮方向。先试香，再决定是否加入自己的常用矩阵。', temp: [20, 35], seasons: ['春季', '夏季'], weather: ['晴天', '多云', '闷热'], scenes: ['日常通勤', '周末出门'], status: 'wishlist', color: '#599aab', spray: '个人试穿参考 3–5 喷，分散佩戴；炎热通勤取较低档，外出再按反馈调整。', source: 'https://us.louisvuitton.com/eng-us/products/imagination-nvprod2970067v/LP0219' },
  { id: 'sycomore', imageSize: '200 ml', image: './assets/sycomore.jpg', brand: 'CHANEL', name: 'Sycomore', cn: '梧桐影木', family: '烟熏木质', notes: ['香根草', '烟熏感', '深色木香'], mood: '干燥的树根与木头，适合沉静的夜。', description: '想买清单里的深色木质方向。它拓展木质体验，温暖潮湿时可以先少量试穿。', temp: [10, 25], seasons: ['秋季', '冬季'], weather: ['多云', '雨天'], scenes: ['约会晚餐', '居家独处'], status: 'wishlist', color: '#626e66', spray: '个人试穿参考 2–4 喷，近距离先取 2 喷，凉爽外出再按实际反馈增加。', source: 'https://www.chanel.com/us/fragrance/p/122300/sycomore-les-exclusifs-de-chanel-eau-de-parfum/' }
];
